version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSGRES_PASSWORD=postgres
      - POSTGES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
